// <auto-generated />
namespace TilerTests.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TravelCacheRemovedLocationFromClocationCache : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TravelCacheRemovedLocationFromClocationCache));
        
        string IMigrationMetadata.Id
        {
            get { return "201911101038245_TravelCacheRemovedLocationFromClocationCache"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
